### ISSUE TITLE
Cuda out of memory: training patchcore on custom dataset

### ISSUE THREAD

**Issue by igsing** [openvinotoolkit/anomalib#372] opened 2022-06-14 21:43 UTC
Training patchcore model (for classification task) quickly fills all GPU memory (32G) and throws an error:

RuntimeError: CUDA out of memory. Tried to allocate 8.29 GiB (GPU 0; 31.75 GiB total capacity; 24.92 GiB already allocated; 2.77 GiB free; 27.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epoch 0:   6%|▋         | 232/3612 [00:12<02:56, 19.15it/s, loss=nan] 

Custom dataset consist of ~7000 256x256 RGB images for training. Changing bath size to a single image still ends with the same error. Training on mvtec dataset goes smoothly.

**Comment by yonafalinie** [comment] 2022-06-15 10:44
I also encounter the same error on my custom datasets. However, what I did was reducing the image_size to 128, 64 or 32 as well depending the algorithm used.
I guess there are some limitation on the number of training images therefore my best guess is reducing the number of images during training might solve the problem.

**Comment by djdameln** [comment] 2022-06-15 11:11
Hi, PatchCore is a memory-intensive algorithm because it stores features extracted from the training set in an internal memory bank. Using a smaller batch size does not solve the problem unfortunately, because the features extracted from each batch still need to be kept in memory.

This is especially a problem for datasets consisting of a large number of images. We are aware of this problem, and it is on our planning to work on memory optimizations for this algorithm. In the mean time, you could try @yonafalinie's suggestions, and use a smaller image size or train with a smaller subset of your training data. Both these modifications would result in a smaller size of the memory bank. Another way to reduce the size of the memory bank is to use a smaller model as backbone, e.g. resnet18.

**Comment by samet-akcay** [comment] 2022-06-15 14:14
This is a duplicate of #203. Closing this to could continue our discussion there. Thanks!

**Closed by samet-akcay** 2022-06-15 14:14 UTC
Labels: Model
