### ISSUE TITLE
[Task]: Why Predicted Heat maps trained using efficient_ad models look strange.

### ISSUE THREAD

**Issue by Xuyilongs** [openvinotoolkit/anomalib#1646] opened 2024-01-17 09:44 UTC
### What is the motivation for this task?

![000](https://github.com/openvinotoolkit/anomalib/assets/106374953/341283fe-7689-4bae-bab2-aad430ed8a1c)
This is the result picture I got when I trained the efficient_ad model using the default data set format, why the predicted heat map here is strange, all green.
![image](https://github.com/openvinotoolkit/anomalib/assets/106374953/2c36b615-b869-4bc9-bfb5-d9ec0cb3c886)
Why is the anomaly_maps data always the same value 0.4975?
![000](https://github.com/openvinotoolkit/anomalib/assets/106374953/4fa36a4a-d324-4c4e-a2c7-328539be00bf)
But on the same data set, using other models such as fastflow, this is what the predicted heat map looks like.

### Describe the solution you'd like

Why is that？

**Comment by blaz-r** [comment] 2024-01-30 16:45
This issue was discussed here: https://github.com/openvinotoolkit/anomalib/discussions/1647

**Comment by samet-akcay** [comment] 2024-02-09 10:27
Closing as it is a duplicate of #1647. Let's continue the discussion there..

**Closed by samet-akcay** 2024-02-09 10:27 UTC
Labels: Task
