### ISSUE TITLE
[Bug]: A bug occurs when you use the patchcore model to train your own data

### ISSUE THREAD

**Issue by praycxy** [openvinotoolkit/anomalib#1853] opened 2024-03-14 05:32 UTC
### Describe the bug

`(base) (.venv) PS C:\patch\anomalib> python tools/train.py --config C:\patch\anomalib\anomalib\models\patchcore\config.yaml
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer. 
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer. 
C:\patch\anomalib\src\anomalib\config\config.py:243: UserWarning: The seed value is now fixed to 0. Up to v0.3.7, the seed was not fixed when the se
ed value was set to 0. If you want to use the random seed, please select `None` for the seed value (`null` in the YAML file) or remove the `seed` ke
y from the YAML file.
  warn(
C:\patch\anomalib\src\anomalib\config\config.py:280: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results 
will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 0 
2024-03-14 13:19:29,764 - anomalib.data - INFO - Loading the datamodule 
2024-03-14 13:19:29,765 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2024-03-14 13:19:29,765 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2024-03-14 13:19:29,767 - anomalib.models - INFO - Loading the model.
2024-03-14 13:19:29,767 - anomalib.models.components.base.anomaly_module - INFO - Initializing PatchcoreLightning model.
C:\patch\anomalib\.venv\Lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and 
predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2024-03-14 13:19:29,773 - anomalib.models.components.feature_extractors.timm - WARNING - FeatureExtractor is deprecated. Use TimmFeatureExtractor in
stead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
2024-03-14 13:19:31,432 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releas
es/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
2024-03-14 13:19:31,633 - anomalib.utils.loggers - INFO - Loading the experiment logger(s) 
2024-03-14 13:19:31,633 - anomalib.utils.callbacks - INFO - Loading the callbacks 
C:\patch\anomalib\src\anomalib\utils\callbacks\__init__.py:153: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2024-03-14 13:19:31,645 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: False, used: False 
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches pe
r epoch will be used..
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will
 be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches wil
l be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches 
will be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at 
the end of the training epoch..
2024-03-14 13:19:31,647 - anomalib - INFO - Training the model.
2024-03-14 13:19:31,654 - anomalib.data.mvtec - INFO - Found the dataset. 
Traceback (most recent call last): 
  File "C:\patch\anomalib\tools\train.py", line 86, in <module> 
    train(args)
  File "C:\patch\anomalib\tools\train.py", line 71, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1051, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1298, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 111, in setup
    self._setup(stage)
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 127, in _setup
    self.train_data.setup()
  File "C:\patch\anomalib\src\anomalib\data\base\dataset.py", line 162, in setup
    self._setup()
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 196, in _setup
    self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 151, in make_mvtec_dataset
    samples.loc[
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 894, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1902, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1987, in _setitem_with_indexer_split_path
    raise ValueError(
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 127, in _setup
    self.train_data.setup()
  File "C:\patch\anomalib\src\anomalib\data\base\dataset.py", line 162, in setup
    self._setup()
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 196, in _setup
    self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 151, in make_mvtec_dataset
    samples.loc[
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 894, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1902, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1987, in _setitem_with_indexer_split_path
    raise ValueError(
ValueError: Must have equal len keys and value when setting with an iterable
`

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

`dataset:
  name: mydatas
  format: mydata
  path: ./datasets/mydatas
  task: segmentation
  category: bottle
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 512 # dimensions to which images are resized (mandatory)
  center_crop: 224 # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
`

### OS information

OS information:
- OS: Windows
- Python version:3.11
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

The model is trained as normal

### Pip/GitHub

pip

### Configuration YAML

```yaml
(base) (.venv) PS C:\patch\anomalib> python tools/train.py --config C:\patch\anomalib\anomalib\models\patchcore\config.yaml
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer. 
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer. 
C:\patch\anomalib\src\anomalib\config\config.py:243: UserWarning: The seed value is now fixed to 0. Up to v0.3.7, the seed was not fixed when the se
ed value was set to 0. If you want to use the random seed, please select `None` for the seed value (`null` in the YAML file) or remove the `seed` ke
y from the YAML file.
  warn(
C:\patch\anomalib\src\anomalib\config\config.py:280: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results 
will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 0 
2024-03-14 13:19:29,764 - anomalib.data - INFO - Loading the datamodule 
2024-03-14 13:19:29,765 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2024-03-14 13:19:29,765 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2024-03-14 13:19:29,767 - anomalib.models - INFO - Loading the model.
2024-03-14 13:19:29,767 - anomalib.models.components.base.anomaly_module - INFO - Initializing PatchcoreLightning model.
C:\patch\anomalib\.venv\Lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and 
predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2024-03-14 13:19:29,773 - anomalib.models.components.feature_extractors.timm - WARNING - FeatureExtractor is deprecated. Use TimmFeatureExtractor in
stead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
2024-03-14 13:19:31,432 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releas
es/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
2024-03-14 13:19:31,633 - anomalib.utils.loggers - INFO - Loading the experiment logger(s) 
2024-03-14 13:19:31,633 - anomalib.utils.callbacks - INFO - Loading the callbacks 
C:\patch\anomalib\src\anomalib\utils\callbacks\__init__.py:153: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2024-03-14 13:19:31,645 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: False, used: False 
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches pe
r epoch will be used..
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will
 be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches wil
l be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches 
will be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at 
the end of the training epoch..
2024-03-14 13:19:31,647 - anomalib - INFO - Training the model.
2024-03-14 13:19:31,654 - anomalib.data.mvtec - INFO - Found the dataset. 
Traceback (most recent call last): 
  File "C:\patch\anomalib\tools\train.py", line 86, in <module> 
    train(args)
  File "C:\patch\anomalib\tools\train.py", line 71, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1051, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1298, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 111, in setup
    self._setup(stage)
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 127, in _setup
    self.train_data.setup()
  File "C:\patch\anomalib\src\anomalib\data\base\dataset.py", line 162, in setup
    self._setup()
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 196, in _setup
    self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 151, in make_mvtec_dataset
    samples.loc[
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 894, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1902, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1987, in _setitem_with_indexer_split_path
    raise ValueError(
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 127, in _setup
    self.train_data.setup()
  File "C:\patch\anomalib\src\anomalib\data\base\dataset.py", line 162, in setup
    self._setup()
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 196, in _setup
    self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 151, in make_mvtec_dataset
    samples.loc[
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 894, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1902, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1987, in _setitem_with_indexer_split_path
    raise ValueError(
ValueError: Must have equal len keys and value when setting with an iterable
```

### Logs

```shell
(base) (.venv) PS C:\patch\anomalib> python tools/train.py --config C:\patch\anomalib\anomalib\models\patchcore\config.yaml
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer. 
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer. 
C:\patch\anomalib\src\anomalib\config\config.py:243: UserWarning: The seed value is now fixed to 0. Up to v0.3.7, the seed was not fixed when the se
ed value was set to 0. If you want to use the random seed, please select `None` for the seed value (`null` in the YAML file) or remove the `seed` ke
y from the YAML file.
  warn(
C:\patch\anomalib\src\anomalib\config\config.py:280: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results 
will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 0 
2024-03-14 13:19:29,764 - anomalib.data - INFO - Loading the datamodule 
2024-03-14 13:19:29,765 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2024-03-14 13:19:29,765 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2024-03-14 13:19:29,767 - anomalib.models - INFO - Loading the model.
2024-03-14 13:19:29,767 - anomalib.models.components.base.anomaly_module - INFO - Initializing PatchcoreLightning model.
C:\patch\anomalib\.venv\Lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and 
predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2024-03-14 13:19:29,773 - anomalib.models.components.feature_extractors.timm - WARNING - FeatureExtractor is deprecated. Use TimmFeatureExtractor in
stead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
2024-03-14 13:19:31,432 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releas
es/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
2024-03-14 13:19:31,633 - anomalib.utils.loggers - INFO - Loading the experiment logger(s) 
2024-03-14 13:19:31,633 - anomalib.utils.callbacks - INFO - Loading the callbacks 
C:\patch\anomalib\src\anomalib\utils\callbacks\__init__.py:153: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2024-03-14 13:19:31,645 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: False, used: False 
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches pe
r epoch will be used..
2024-03-14 13:19:31,646 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will
 be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches wil
l be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches 
will be used..
2024-03-14 13:19:31,647 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at 
the end of the training epoch..
2024-03-14 13:19:31,647 - anomalib - INFO - Training the model.
2024-03-14 13:19:31,654 - anomalib.data.mvtec - INFO - Found the dataset. 
Traceback (most recent call last): 
  File "C:\patch\anomalib\tools\train.py", line 86, in <module> 
    train(args)
  File "C:\patch\anomalib\tools\train.py", line 71, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1051, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1298, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 111, in setup
    self._setup(stage)
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 127, in _setup
    self.train_data.setup()
  File "C:\patch\anomalib\src\anomalib\data\base\dataset.py", line 162, in setup
    self._setup()
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 196, in _setup
    self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 151, in make_mvtec_dataset
    samples.loc[
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 894, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1902, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1987, in _setitem_with_indexer_split_path
    raise ValueError(
  File "C:\patch\anomalib\src\anomalib\data\base\datamodule.py", line 127, in _setup
    self.train_data.setup()
  File "C:\patch\anomalib\src\anomalib\data\base\dataset.py", line 162, in setup
    self._setup()
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 196, in _setup
    self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\patch\anomalib\src\anomalib\data\mvtec.py", line 151, in make_mvtec_dataset
    samples.loc[
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 894, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1902, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\patch\anomalib\.venv\Lib\site-packages\pandas\core\indexing.py", line 1987, in _setitem_with_indexer_split_path
    raise ValueError(
ValueError: Must have equal len keys and value when setting with an iterable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment] 2024-03-20 23:14
Duplicate of #1860

**Closed by samet-akcay** 2024-03-20 23:14 UTC
