### ISSUE TITLE
Model Loader Callback

### ISSUE THREAD

**Issue by shakib-root** [openvinotoolkit/anomalib#349] opened 2022-06-07 07:33 UTC
**Is your feature request related to a problem? Please describe.**
  - Currently, the Pytorch Lightning(PL) trainer uses a callback `LoadModelCallback` from `anomalib/utils/callbacks/model_loader.py` where it uses Pytorch's `torch.load` function to load the best weights which may cause device-related issues (trained on GPU, testing/predicting on CPU).

**Describe the solution you'd like**
  - I suggest removing Pytorch's `torch.load` function from `LoadModelCallback` and letting the PL trainer handle this issue.
 ```python
trainer.test(model=model, datamodule=datamodule, ckpt_path='best')    #or
trainer.test(model=model, datamodule=datamodule, ckpt_path='$path_to_the_checkpoint_user_wish_to_test')
```
 ```python
trainer.predict(model=model, datamodule=datamodule, ckpt_path='best')    #or
trainer.predict(model=model, datamodule=datamodule, ckpt_path='$path_to_the_checkpoint_user_wish_to_predict')
```

Reference: [[PL docs](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer.test)]

**Comment by djdameln** [comment] 2022-06-07 08:30
Thanks for your suggestion! This could indeed be a better way of loading the model weights, though we will have to investigate if this would lead to any unwanted/unexpected behavior. We'll have a look and post any findings here.

**Comment by samet-akcay** [comment] 2022-06-07 08:33
Hi @shakib-root, the reason why we used this was because there was a bug in PL model loading in its earlier versions. We were unable to achieve the same performance as training. We could try again now.

**Comment by ashwinvaidya17** [comment] 2022-12-29 09:04
I am closing this as this change has been merged to the feature branch and will be merged to main soon.

**Closed by ashwinvaidya17** 2022-12-29 09:04 UTC
Labels: Enhancement, Model
