### ISSUE TITLE
On Test Model load callback does not load recently created model

### ISSUE THREAD

**Issue by blakshma** [openvinotoolkit/anomalib#75] opened 2022-01-18 05:01 UTC
**Model is loading default model from config file**
- While training model multiple times, new model file version gets created however the old model gets loaded for testing and results are evaluated with the old model. Any change in data or code does not get reflected in the results. 

**To Reproduce**
1. Train a model with subset of images
2. Retrain with complete dataset
3. Evaluate performance

**Comment by samet-akcay** [comment] 2022-01-18 05:14
@blakshma can you also provide the cli-commands to produce this

**Comment by blakshma** [comment] 2022-01-18 05:26
@samet-akcay it can be any model training. For instance,
python tools/train.py --model patchcore

**Comment by ashwinvaidya17** [comment] 2022-04-04 11:17
Duplicate of #63

**Closed** 2022-04-04 11:17 UTC
Labels: Bug, Callbacks
