### ISSUE TITLE
Getting the segmentation results during testing

### ISSUE THREAD

**Issue by FaDavid98** [openvinotoolkit/anomalib#400] opened 2022-07-04 09:42 UTC
I saw that during training the model finds the best threhold, and shows the segmentation results for the testing images. I am wondering, how could I get those segemntation results in the testing phase. 
I mean i want to run the inference.py file and get those segmentation result for the used image.
Thanks for your answer.

**Comment by nguyenanhtuan1008** [comment] 2022-07-08 00:22
@FaDavid98 Do you get the solution?

**Comment by samet-akcay** [comment] 2022-07-11 11:57
Hi @FaDavid98, what sort of result woulld you like to get? A mask, polygons? Any other format?

**Comment by samet-akcay** [comment] 2022-07-11 17:02
Duplicate of #294. Let's continue our discussion there.

**Closed by samet-akcay** 2022-07-11 17:02 UTC
