### ISSUE TITLE
Can't convert fastflow from .onnx to openvino format.

### ISSUE THREAD

**Issue by wulongjian** [openvinotoolkit/anomalib#706] opened 2022-11-10 11:25 UTC
**Describe the bug**
I use fastflow (ResNet18) to train the mvtec dataset, and I want convert the trained model to the openvino format, but I get errors as follows.
*Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.LayerNorm.LayerNorm'>)": The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()*

**My config optimization params as follows**
optimization:
   export_mode: "openvino"

**Screenshots**

![image](https://user-images.githubusercontent.com/26458219/201078275-7182ac33-2736-4fd6-8aa4-a815f32aff3e.png)
![image](https://user-images.githubusercontent.com/26458219/201079696-9bc620dc-a3ba-4ea6-8680-137328f3117d.png)

**Hardware and Software Configuration**

- OS: Windows10
-torch: 1.12.0
- pytorch-lightning: 1.6.5
-anomalib: 0.3.7
- OpenVINO Version [v2021.4.2]
- onnx: 1.12.0

**Additional context**

Is it  not supported FastFlow model convertation from onnx to openvino currently or am I doing something wrong?

**Comment by samet-akcay** [comment] 2022-11-22 05:31
@wulongjian, thanks for reporting this. Looks like this has already been reported.

Duplicate of #631

**Closed by samet-akcay** 2022-11-22 05:31 UTC
