### ISSUE TITLE
Training a model with only normal data, gettting "RuntimeError: Found 0 abnormal images"

### ISSUE THREAD

**Issue by toon-vc** [openvinotoolkit/anomalib#691] opened 2022-11-07 09:09 UTC
**Describe the bug**

When training a model with only normal images, getting "RuntimeError: Found 0 abnormal images "

![image](https://user-images.githubusercontent.com/16069303/200269184-0530d9e3-5107-4499-a2a4-85bacccfe6e0.png)

The problem can be fixed by removing the abnormal dir in *make_dataset* in the folder module:
`dirs = {"normal": normal_dir}`
instead of 
`dirs = {"normal": normal_dir, "abnormal": abnormal_dir}`

If I do this, training finishes successfully and I get a good model.

Should the abnormal_dir be made Optional, and the abnormal_dir left out of dirs when it is not specified? Or can this be due to issues in config/setup? 

**To Reproduce**

Train a PatchCore model without any abnormal images.

**Expected behavior**

A successful training run. 

**Hardware and Software Configuration**

- OS: Ubuntu
- anomalib: 0.3.7

**Comment by samet-akcay** [comment] 2022-11-07 09:21
Duplicate of #277.

@toon-vc, this is something we are currently working on. It will be available [here](https://github.com/openvinotoolkit/anomalib/blob/feature/datamodules/tools/train.py#L66-L70) once we merge this [feature branch](https://github.com/openvinotoolkit/anomalib/tree/feature/datamodules) to main.

**Closed by samet-akcay** 2022-11-07 09:21 UTC
