### ISSUE TITLE
[Task]: model.xml cannot be opened!

### ISSUE THREAD

**Issue by RustX2802** [openvinotoolkit/anomalib#1263] opened 2023-08-11 05:03 UTC
### What is the motivation for this task?

After successfully training a patchcore model, I would like to get the inference in OpenVINO IR. But I get the following error:

![image](https://github.com/openvinotoolkit/anomalib/assets/72299347/528bb490-6502-4844-a9ed-307a3e7fb13a)

despite having all necessary files:

![image](https://github.com/openvinotoolkit/anomalib/assets/72299347/8a6e0f83-b961-40ad-99d5-16438ffafee1)

### Describe the solution you'd like

I would like to infer my model with openvino without any issues

### Additional context

Here is my system info:

`OS: Windows 11 Pro 64-bit,
Processor: 11th Gen Intel(R) Core(TM)i9-11900 @ 2.50GHz
Memory: 32768MB`

I'm running Python 3.10.9

I'm not sure if the following statement from OpenVino System Requirements causes the issue:
![image](https://github.com/openvinotoolkit/anomalib/assets/72299347/7d10a28a-4c85-4821-bd05-6e6cd6844d08)

Any thoughts, please?

**Comment by samet-akcay** [comment] 2023-08-11 05:39
Hi @RustX2802, I checked this on a Linux machine and cannot reproduce. As you pointed out, it is quite likely to be a windows issue. 

@ashwinvaidya17, would it be possible to check this on a Windows machine?

**Comment by ashwinvaidya17** [comment] 2023-08-11 10:46
@RustX2802 can you pull the main branch and check again? OpenVINO inference works on my system. I am using Windows 10 with python 3.10.

**Comment by blaz-r** [comment] 2023-08-11 19:05
I have Windows 11 and get the following:
```
RuntimeError: Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\inference\src\core.cpp:117:
Failed to allocate 78981041216 bytes of memory
```
😅

**Comment by RustX2802** [comment] 2023-08-14 00:26
> @RustX2802 can you pull the main branch and check again? OpenVINO inference works on my system. I am using Windows 10 with python 3.10.

@ashwinvaidya17 actually, I pulled the main branch initially by `git clone https://github.com/openvinotoolkit/anomalib.git`. I will try to re-implement it later today and will let you know.

**Comment by RustX2802** [comment] 2023-08-14 05:08
@ashwinvaidya17 @samet-akcay sorry, it seems I had missed one of the folders. After double-checking the tree-folder, the subject issue is resolved, but now I face the same issue as @blaz-r 

`RuntimeError: Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\inference\src\core.cpp:117:
Failed to allocate 78981041216 bytes of memory`

Is this something I have to refer to the issue #967?

**Comment by samet-akcay** [comment] 2023-08-14 11:39
@RustX2802, I have the same suspicion that this would be related to #967.

@blaz-r, would you be able to check if you still have the error when you modify the cdist computation based on what is suggested in #967?

**Comment by blaz-r** [comment] 2023-08-14 12:04
Yeah, sure. I'll get back to you with results.

**Comment by blaz-r** [comment] 2023-08-14 15:24
@samet-akcay @RustX2802 using the modified cdist function from #967 work. I will open a PR with it.

**Comment by samet-akcay** [comment] 2023-08-15 08:55
@RustX2802 I'm closing this issue, assuming that #1267 should fix this. Let us know if you face any issues.

**Closed by samet-akcay** 2023-08-15 08:55 UTC
Labels: Task

**Comment by RustX2802** [comment] 2023-08-16 00:39
Sorry for the late reply! Following the instructions from #967, I was able to train the patchcore with the revised cdist function successfully, although haven't tested it on inference yet. Thank you all guys for your efforts and support.
