### ISSUE TITLE
[Bug]: trainer.fit() crushes through the use of torchmetrics

### ISSUE THREAD

**Issue by NoamKaufmanLin** [openvinotoolkit/anomalib#925] opened 2023-02-21 12:57 UTC
### Describe the bug

Running trainer.fit() over custom (folder) data is crushing through the use of torchmetrics:
precision, recall, thresholds = super().compute()  --> index 1708598 is out of bounds for dimension 0 with size 903168
(If I upgrade to the latest torchmetrics I encounter a different bug.)

### Dataset

Folder

### Model

PatchCore

### Steps to reproduce the behavior

1. Install Anomalib through cloning + pip install e

2. Custom config to have user dataset (folder), patchcore base params

3. Get dataloaders using:
datamodule = get_datamodule(config)
datamodule.setup()
datamodule.prepare_data()
train_loader = datamodule.train_dataloader()
val_loader = datamodule.val_dataloader()
test_loader = datamodule.test_dataloader()

4. Define trainer using config
trainer = Trainer(**config.trainer, logger=experiment_logger, callbacks=callbacks)

5. Fit the trainer
trainer.fit(model=model, train_dataloaders=train_data_loader, val_dataloaders=val_data_loader)

### OS information

OS information:
- Python version: 3.8.0
- PyTorch version: 1.12.0
- torchmetrics version: 0.10.3
- I'm using a custom dataset
- I'm using a custom dataset

### Expected behavior

super().compute() yields the precision, recall and thresholds

### Pip/GitHub

GitHub

### What version/branch did you use?

main

### Configuration YAML

```yaml
dataset:
  name: dataset_name
  format: folder
  path:  tryout_dataset # data_path
  normal_dir: train # name of the folder containing normal images.
  abnormal_dir: def # name of the folder containing abnormal images.
  mask: masks/def # optional
  normal_test_dir: normal # optional
  task: segmentation # classification or segmentation
  extensions: null
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  image_size: 512 # dimensions to which images are resized (mandatory)
  center_crop: 224 # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: resnet18
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results
  unique_dir: True

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
#  log_gpu_memory: null
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.
```

### Logs

```shell
File "/home/AD/ad/trainer_anomalib.py", line 121, in train
    anomalib_trainer.fit(model=model, train_dataloaders=train_data_loader, val_dataloaders=val_data_loader)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/home/AD/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/AD/ad/anomalib/anomalib/models/components/base/anomaly_module.py", line 145, in validation_epoch_end
    self._compute_adaptive_threshold(outputs)
  File "/home/AD/ad/anomalib/anomalib/models/components/base/anomaly_module.py", line 164, in _compute_adaptive_threshold
    self.pixel_threshold.compute()
  File "/home/AD/venv/lib/python3.8/site-packages/torchmetrics/metric.py", line 534, in wrapped_func
    value = compute(*args, **kwargs)
  File "/home/AD/ad/anomalib/anomalib/utils/metrics/anomaly_score_threshold.py", line 54, in compute
    precision, recall, thresholds = super().compute()
  File "/home/AD/venv/lib/python3.8/site-packages/torchmetrics/classification/precision_recall_curve.py", line 578, in compute
    return _precision_recall_curve_compute(preds, target, self.num_classes, self.pos_label)
  File "/home/AD/venv/lib/python3.8/site-packages/torchmetrics/functional/classification/precision_recall_curve.py", line 967, in _precision_recall_curve_compute
    return _precision_recall_curve_compute_single_class(preds, target, pos_label, sample_weights)
  File "/home/AD/venv/lib/python3.8/site-packages/torchmetrics/functional/classification/precision_recall_curve.py", line 847, in _precision_recall_curve_compute_single_class
    fps, tps, thresholds = _binary_clf_curve(
  File "/home/AD/venv/lib/python3.8/site-packages/torchmetrics/functional/classification/precision_recall_curve.py", line 58, in _binary_clf_curve
    target = target[desc_score_indices]
IndexError: index 1708598 is out of bounds for dimension 0 with size 903168
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdelsalamHaa** [comment] 2023-05-31 02:58
Hi @NoamKaufmanLin 
I have the same issue, any Update on this ?

**Comment by stopsilver** [comment] 2023-06-02 03:03
@NoamKaufmanLin @AbdelsalamHaa 
I have the same problem with ganomaly. The dataset worked fine when using patchcore.
Any update?

**Comment by NoamKaufmanLin** [comment] 2023-06-06 19:13
Haven't tried since

**Comment by samet-akcay** [comment] 2023-09-27 11:57
HI everyone, I've tried patchcore and ganomaly on custom datasets. Both worked fine, so it seems that it not reproducable anymore. 

Make sure you have consistent image-mask pairs. The dimension mismatch might potentially be due to that. 
Also make sure that you switch the task to classification when you train ganomaly, which does not support segmentation task.

I'm closing this issue. Feel free to re-open if you think that the issue still persists.

**Closed by samet-akcay** 2023-09-27 11:57 UTC
