### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by lekshmijk** [openvinotoolkit/anomalib#753] opened 2022-12-01 11:56 UTC
Hi, I've been able to train the MVTec dataset on multiple models earlier last week, but today as I was trying to do it again, I'm getting some errors and I'm not sure what's the matter right now..
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45484074/205046712-c36b560a-60c1-427d-9a9e-feb2c5cb428b.png)

**Comment by ashwinvaidya17** [comment] 2022-12-01 12:42
Closing as duplicate of #750

**Closed by ashwinvaidya17** 2022-12-01 12:42 UTC
