### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by vishalk2999** [openvinotoolkit/anomalib#985] opened 2023-03-27 09:12 UTC
When running the patchcore model on the MvTEC dataset, no runtime errors during training, but I get this error when trying to train using a custom dataset.

```
To use wandb logger install it using `pip install wandb`
/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/config/config.py:238: UserWarning: The seed value is now fixed to 0. Up to v0.3.7, the seed was not fixed when the seed value was set to 0. If you want to use the random seed, please select `None` for the seed value (`null` in the YAML file) or remove the `seed` key from the YAML file.
  warn(
/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/config/config.py:275: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 0
2023-03-27 14:26:50,464 - anomalib.data - INFO - Loading the datamodule
2023-03-27 14:26:50,465 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-03-27 14:26:50,465 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-03-27 14:26:50,465 - anomalib.models - INFO - Loading the model.
2023-03-27 14:26:50,465 - anomalib.models.components.base.anomaly_module - INFO - Initializing PatchcoreLightning model.
/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2023-03-27 14:26:50,470 - anomalib.models.components.feature_extractors.timm - WARNING - FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
2023-03-27 14:26:51,838 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
2023-03-27 14:26:52,039 - anomalib.utils.loggers - INFO - Loading the experiment logger(s)
2023-03-27 14:26:52,039 - anomalib.utils.callbacks - INFO - Loading the callbacks
/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/utils/callbacks/__init__.py:142: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2023-03-27 14:26:52,060 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: True (cuda), used: True
2023-03-27 14:26:52,060 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2023-03-27 14:26:52,060 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2023-03-27 14:26:52,060 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2023-03-27 14:26:52,061 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
2023-03-27 14:26:52,061 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2023-03-27 14:26:52,061 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2023-03-27 14:26:52,061 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
2023-03-27 14:26:52,061 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2023-03-27 14:26:52,061 - anomalib - INFO - Training the model.
2023-03-27 14:26:52,237 - anomalib.data.base.datamodule - INFO - No normal test images found. Sampling from training set using a split ratio of 0
/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:613: UserWarning: Checkpoint directory /mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/results/patchcore/mpi/run/weights exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
2023-03-27 14:26:52,652 - pytorch_lightning.accelerators.cuda - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
2023-03-27 14:26:52,656 - pytorch_lightning.callbacks.model_summary - INFO - 
  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | image_threshold       | AnomalyScoreThreshold    | 0     
1 | pixel_threshold       | AnomalyScoreThreshold    | 0     
2 | model                 | PatchcoreModel           | 24.9 M
3 | image_metrics         | AnomalibMetricCollection | 0     
4 | pixel_metrics         | AnomalibMetricCollection | 0     
5 | normalization_metrics | MinMax                   | 0     
-------------------------------------------------------------------
24.9 M    Trainable params
0         Non-trainable params
24.9 M    Total params
99.450    Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                    | 0/16 [00:00<?, ?it/s]/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py:138: UserWarning: `training_step` returned `None`. If this was on purpose, ignore this warning...
  self.warning_cache.warn("`training_step` returned `None`. If this was on purpose, ignore this warning...")
Epoch 0:  69%|████████████████2023-03-27 14:26:53,916 - anomalib.models.patchcore.lightning_model - INFO - Aggregating the embedding extracted from the training set.s]
2023-03-27 14:26:53,917 - anomalib.models.patchcore.lightning_model - INFO - Applying core-set subsampling to get the embedding.
   Traceback (most recent call last):                                                                                  | 0/5 [00:00<?, ?it/s]
  File "tools/train.py", line 75, in <module>
    train()
  File "tools/train.py", line 61, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/models/patchcore/lightning_model.py", line 109, in validation_step
    anomaly_maps, anomaly_score = self.model(batch["image"])
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/models/patchcore/torch_model.py", line 90, in forward
    anomaly_map = self.anomaly_map_generator(patch_scores)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/models/patchcore/anomaly_map.py", line 55, in forward
    anomaly_map = self.compute_anomaly_map(patch_scores)
  File "/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/models/patchcore/anomaly_map.py", line 38, in compute_anomaly_map
    anomaly_map = self.blur(anomaly_map)
  File "/home/vk/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/anomalib/models/components/filters/blur.py", line 87, in forward
    output = F.conv2d(input_tensor, self.kernel, groups=self.channels, padding=0, stride=1)
RuntimeError: GET was unable to find an engine to execute this computation
Epoch 0:  69%|██████▉   | 11/16 [00:10<00:04,  1.03it/s, loss=nan]
```

config file used :

```
dataset:
  name: data
  format: folder
  path: /mnt/8014A82114A81C62/Vishal/Anomaly-MPI/anomalib-0.4.0/custom_dataset
  normal_dir: Good # name of the folder containing normal images.
  abnormal_dir: Anomaly # name of the folder containing abnormal images.
  normal_test_dir: null # name of the folder containing normal test images.
  task: segmentation # classification or segmentation
  mask: Mask
  extensions: null
  normalization: imagenet
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 256
  train_batch_size: 8
  test_batch_size: 8
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: true
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle

```

**Comment by samet-akcay** [comment] 2023-04-11 21:34
@vishalk2999, can you check your pytorch and cuda versions? I haven't experienced this issue before, but based on a quick search, it sounds like it might be related to that. 
https://stackoverflow.com/questions/75776895/runtimeerror-get-was-unable-to-find-an-engine-to-execute-this-computation-when

https://github.com/microsoft/visual-chatgpt/issues/283

**Comment by vishalk2999** [comment] 2023-04-12 09:29
@samet-akcay the cuda version in nvidia-smi and nvcc are matching and the cuda version is 11.3. Moreover, I am able to train using GPU when I am using the default config file for training patchcore using MvTEC dataset. I am getting this issue only when I am using a custom dataset

**Comment by samet-akcay** [comment] 2023-08-15 14:44
Please see this discussion
https://stackoverflow.com/questions/75776895/runtimeerror-get-was-unable-to-find-an-engine-to-execute-this-computation-when

This could potentially be due to your cuda installation or gpu memory issue when you try to fit a large custom dataset into your memory.

I'm closing this since this is not a bug. Feel free to re-open if you face any other problems

**Closed by samet-akcay** 2023-08-15 14:44 UTC

**Comment by kimminchol1** [comment] 2024-04-15 06:47
Try entering the code below.

> $ conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
