### ISSUE TITLE
[Bug]: System unresponsive while executing class SpawnProcess in context.py

### ISSUE THREAD

**Issue by skaderbe** [openvinotoolkit/anomalib#2044] opened 2024-05-06 10:41 UTC
### Describe the bug

Anomalib library is installed.

Copy-pasted the code listed in "Training" section of Anomalib webpage. Program is running however there is no output.

Debugging the code with breakpoints indicate system becoming unresponsive while executing class SpawnProcess in context.py (C:\users\admin\anaconda3\envs\anomalib_env\lib\multiprocessing\context.py line 332).

Appreciate help in overcoming the issue.

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

Debugging the code with breakpoints in context.py (C:\users\admin\anaconda3\envs\anomalib_env\lib\multiprocessing\context.py line 332).

### OS information

Win 64-bit operating system, x64-based processor
Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
16.0 GB (15.8 GB usable)
Python version 3.12.3
Anomalib version 1,0.1
PyTorch version 2.2.3

### Expected behavior

Training of the model.

### Pip/GitHub

pip

### Configuration YAML

```yaml
Suggest the local folder and name of YAML file required.
```

### Logs

```shell
No logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexriedel1** [comment] 2024-05-06 20:36
What you are describing is unrelated to anomalib. You have tracked the "error" down to a process that is happening in pythons multiprocessing package.
Can you please show the exact code you are executing and the exact output?

**Comment by skaderbe** [comment] 2024-05-07 04:47
Executing the following code. Code shared in [1],
from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine
datamodule = MVTec()
model = Patchcore()
engine = Engine()
engine.fit(datamodule=datamodule, model=model)

Executing the above code line by line in debug mode. System becomes unresponsive while executing line number 337 in context.py [2]. Executing a bit further the system becomes unresponsive in line number 95 in popen_spawn_win32.py [3]. Screenshots attached.

1. https://anomalib.readthedocs.io/en/v1.0.1/markdown/get_started/anomalib.html
2. C:\users\admin\anaconda3\envs\anomalib_env\lib\multiprocessing\context.py
3. C:\users\admin\anaconda3\envs\anomalib_env\lib\multiprocessing\popen_spawn_win32.py
![pg1](https://github.com/openvinotoolkit/anomalib/assets/18460699/2df2cf5f-8a7a-4436-99b9-6ecba9bbe481)
![pg2](https://github.com/openvinotoolkit/anomalib/assets/18460699/32818807-94fd-413d-bcbd-61eec0d7918a)

**Comment by alexriedel1** [comment] 2024-05-07 08:44
Can you try to run the code outside of spyder? In a simple console e.g.

**Comment by samet-akcay** [comment] 2024-05-07 11:48
@skaderbe, what you are sharing is not part of anomalib. Maybe you could set `num_workers=1` in your datamodule to avoid multiprocessing when debugging

**Comment by samet-akcay** [comment] 2024-05-09 04:53
Closing this as it is not a bug. Feel free to re-open if you think it is still an issue. Thanks

**Closed by samet-akcay** 2024-05-09 04:53 UTC

**Comment by skaderbe** [comment] 2024-05-11 06:11
> Can you try to run the code outside of spyder? In a simple console e.g.

Installed Python 3.11.9.
Installed Anomalib and associated libraries
Downloaded MVTec datasets

Executing the training code from Anomalib webpage leaves the system unresponsive.

![Untitled](https://github.com/openvinotoolkit/anomalib/assets/18460699/05e527db-ef04-4171-b65b-5ad0dcbcc07a)

**Comment by skaderbe** [comment] 2024-05-12 16:05
> Closing this as it is not a bug. Feel free to re-open if you think it is still an issue. Thanks

Followed advice suggested by @alexriedel1 . However still the problem persists. Request to kindly re-open the issue and advise an solution. Thanks.

**Comment by samet-akcay** [comment] 2024-05-12 20:22
@skaderbe you could try `datamodule = MVTec(num_workers=1)` when debugging your code. You could create Q&A in discussions but this is not a bug or issue
