### ISSUE TITLE
Tile with PatchCore OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by onkarkris** [openvinotoolkit/anomalib#2207] opened 2024-07-23 05:09 UTC
I am trying to run PatchCore with Tile operation as in the code
`input_tensor` = self.tiler.tile(input_tensor)`
I define self.tiler = Tiler(tile_size=448,stride=400)
Input_tensor before tiling torch.Size([1, 3, 1024, 1024]) and after tiling torch.Size([9, 3, 448, 448])

As soon as training starts it gives error 
> Tile with PatchCore OutOfMemoryError: CUDA out of memory.

Config in my case 
`seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
normalization:
  normalization_method: MIN_MAX
task: SEGMENTATION
metrics:
  image:
  - F1Score
  - AUROC
  pixel: null
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5
      thresholds: null
      ignore_index: null
      validate_args: true
      compute_on_cpu: false
      dist_sync_on_step: false
      sync_on_compute: true
      compute_with_cache: true
logging:
  log_graph: false
default_root_dir: results
ckpt_path: null
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2 #wide_resnet50_2
    layers:
    - layer2
    - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.01
    num_neighbors: 9
data:
  class_path: anomalib.data.MVTec
  init_args:
    root: /home/ubuntu/  
    category: apple_paper 
    train_batch_size: 1
    eval_batch_size: 1
    num_workers: 8
    image_size: null
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: FROM_DIR
    test_split_ratio: 0.2
    val_split_mode: SAME_AS_TEST
    val_split_ratio: 0.5
    seed: null`

**Comment by onkarkris** [comment] 2024-07-24 03:30
> Hello, can you please try to run it on less images or with lower resolution? The problem is probably due to the high memory requirements of PatchCore, during training it processes extracted features from the whole training dataset.

Thanks for your reply! In my case, the anomaly sizes are very small. Running on a lower resolution will reduce them to just a few pixels (10-20 pixels). I'm curious if anyone has successfully run PatchCore with tile operations.

**Comment by abc-125** [comment] 2024-07-24 15:39
Does it work for you without tiling? Again, it can be a PatchCore problem due to high memory requirements of this model.

**Comment by alexriedel1** [comment] 2024-07-24 20:47
you need more gpu memory i guess
or smaller images resolution or less images. 
many images + high resolution = lots of gpu memory

**Comment by JinYuannn** [comment] 2024-07-25 06:34
you can reduce `coreset_sampling_ratio` to 0.01 or 0.001, but this may lead to poor performance.

**Comment by samet-akcay** [comment] 2024-07-25 09:14
I agree with the insights by @abc-125, @alexriedel1 and @JinYuannn. This is probably not an issue but more related to the nature of Patchcore. 

You could potentially try tiling ensemble, but not sure about the current state of the PR. @blaz-r any insights?
https://github.com/openvinotoolkit/anomalib/pull/1226

**Comment by blaz-r** [comment] 2024-07-25 09:16
The tiled ensemble PR is still not 100% there. The training with v1 should work, but it's not all tested. I'm really busy right now but I'll try to get that sorted asap.

**Comment by alexriedel1** [comment] 2024-07-25 09:16
> you can reduce `coreset_sampling_ratio` to 0.01 or 0.001, but this may lead to poor performance.

This probably won't help, because all the image embeddings need to fit on the gpu memory before the actual coreset sampling

**Comment by onkarkris** [comment] 2024-07-26 01:27
@samet-akcay @alexriedel1 @blaz-r @abc-125 
Example use case  --> 
Experiment 1: Anomalib 
Code used --
[https://github.com/openvinotoolkit/anomalib/blob/d1f824a5798262891dbbe583fb291e1cf9aa7d2a/src/anomalib/models/image/patchcore/torch_model.py](url)
`Line 75: input_tensor = self.tiler.tile(input_tensor)`

`self.tiler = Tiler(tile_size=128,stride=128)
coreset_sampling_ratio: 0.01
Image before/after tiling: torch.Size([1, 3, 1024, 1024]) ---> torch.Size([64, 3, 128, 128])`
Error: ![image](https://github.com/user-attachments/assets/d081d82f-6746-4b33-ab52-fb0a878e4ed1)

`self.tiler = Tiler(tile_size=248, stride=248)
coreset_sampling_ratio: 0.001
Image before/after tiling: torch.Size([1, 3, 1024, 1024]) ---> torch.Size([25, 3, 248, 248])
Error: ![image](https://github.com/user-attachments/assets/e066ebf5-21ed-4209-acc1-75092e1cfe41)


Experiment 2: Official PatchCore repository 
Code used --
Incorporated tiling operation in official repository of PatchCore 
[https://github.com/amazon-science/patchcore-inspection](url)

tiler = Tiler(tile_size=128,stride=128)
coreset_sampling_ratio: 0.01
Image before/after tiling: torch.Size([1, 3, 1024, 1024]) ---> torch.Size([64, 3, 128, 128])`
Error: ![image](https://github.com/user-attachments/assets/5821fb68-2116-449d-bcc5-880859956207)

Experiment 3
PatchCore ensemble as mentioned [https://github.com/openvinotoolkit/anomalib/pull/1226/files/dac985fac8cba8644c56cf9c5dd58adaeb651afd#diff-21aa73a1cc1f2758f5b4d44477721b0b6fd00b78976dd91ea019dd9d95624e52](url)
tiler = Tiler(tile_size=128,stride=128)

Error: `File "/home/ubuntu/anomalib_tile/tools/tiled_ensemble/ensemble_functions.py", line 73, in __call__ coll_batch["image"] = tiled_images[self.tile_index] IndexError: index 8 is out of bounds for dimension 1 with size 8


Summary: I think changing the hyperparameters can't solve the issue. By design, it's difficult to use tiling with PatchCore. I'm just wondering if anyone has actually tried using tiling with PatchCore on 1024-sized images (50-60 images)?
`

**Comment by alexriedel1** [comment] 2024-07-26 07:18
> @samet-akcay @alexriedel1 @blaz-r @abc-125
> 
> **I think changing the hyperparameters can't solve the issue. By design, it's difficult to use tiling with PatchCore. I'm just wondering if anyone has successfully used tiling or ensemble tiling with PatchCore on 1024-sized images (50-60 images)?**
> 
> Experiment Details --> Experiment 1: Anomalib Code used -- [https://github.com/openvinotoolkit/anomalib/blob/d1f824a5798262891dbbe583fb291e1cf9aa7d2a/src/anomalib/models/image/patchcore/torch_model.py](url) `Line 75: input_tensor = self.tiler.tile(input_tensor)`
> 
> `self.tiler = Tiler(tile_size=128,stride=128) coreset_sampling_ratio: 0.01 Image before/after tiling: torch.Size([1, 3, 1024, 1024]) ---> torch.Size([64, 3, 128, 128])` Error: ![image](https://private-user-images.githubusercontent.com/13046499/352329876-d081d82f-6746-4b33-ab52-fb0a878e4ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Nzg0NTAsIm5iZiI6MTcyMTk3ODE1MCwicGF0aCI6Ii8xMzA0NjQ5OS8zNTIzMjk4NzYtZDA4MWQ4MmYtNjc0Ni00YjMzLWFiNTItZmIwYTg3OGU0ZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZWMxNDhmYmM0M2M5NmRmZmViMzQ4ZDcwNTkyN2YxNDU5NTljMjMxMDE0NzZhMDNlMTYzMzhjN2Y0NWZhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeirocs1eH0aEE_SifYOCApz45fP3Xik4u9BdDGh95I)
> 
> `self.tiler = Tiler(tile_size=248, stride=248) coreset_sampling_ratio: 0.001 Image before/after tiling: torch.Size([1, 3, 1024, 1024]) ---> torch.Size([25, 3, 248, 248]) Error: ![image](https://private-user-images.githubusercontent.com/13046499/352330334-e066ebf5-21ed-4209-acc1-75092e1cfe41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Nzg0NTAsIm5iZiI6MTcyMTk3ODE1MCwicGF0aCI6Ii8xMzA0NjQ5OS8zNTIzMzAzMzQtZTA2NmViZjUtMjFlZC00MjA5LWFjYzEtNzUwOTJlMWNmZTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZmRmYmJhM2Y2MGFlNzUxM2ZlNDg3NGY0ZDZjNDU0ZTQ1YjE0ZjI4MTQzOTA2NjM4NzJkMjBjODc0MThlMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vGCwp1oEds9pRPrC4DhNPdW72uj5NTTd3C3bvXZ4yWs)
> 
> Experiment 2: Official PatchCore repository Code used -- Incorporated tiling operation in official repository of PatchCore [https://github.com/amazon-science/patchcore-inspection](url)
> 
> tiler = Tiler(tile_size=128,stride=128) coreset_sampling_ratio: 0.01 Image before/after tiling: torch.Size([1, 3, 1024, 1024]) ---> torch.Size([64, 3, 128, 128])` Error: ![image](https://private-user-images.githubusercontent.com/13046499/352332180-5821fb68-2116-449d-bcc5-880859956207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Nzg0NTAsIm5iZiI6MTcyMTk3ODE1MCwicGF0aCI6Ii8xMzA0NjQ5OS8zNTIzMzIxODAtNTgyMWZiNjgtMjExNi00NDlkLWJjYzUtODgwODU5OTU2MjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczODBmMTIwMjRhZWVjYjRjNmRkY2MxNWY4NGUxYTY1MWVhYzNkM2UzYjA5YjUxMDg1ODA2YjczOTc0M2YyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Q_LwRHTanK8E5IgxPanHeYiC74LQUJ3ltQJOk-TDVY)
> 
> Experiment 3 PatchCore ensemble as mentioned [https://github.com/openvinotoolkit/anomalib/pull/1226/files/dac985fac8cba8644c56cf9c5dd58adaeb651afd#diff-21aa73a1cc1f2758f5b4d44477721b0b6fd00b78976dd91ea019dd9d95624e52](url) tiler = Tiler(tile_size=128,stride=128)
> 
> Error: `File "/home/ubuntu/anomalib_tile/tools/tiled_ensemble/ensemble_functions.py", line 73, in **call** coll_batch["image"] = tiled_images[self.tile_index] IndexError: index 8 is out of bounds for dimension 1 with size 8

Like said before the problem is your limited GPU memory. 60 images of 1024x1024 become 3840 tiles of 128x128 and thats a much. Try to find the maximum number of images your GPU memory can handle. Start with 5 of the 1024x1024 tiled images and then try to increase for example.

**Comment by blaz-r** [comment] 2024-07-26 10:40
For such large images, the tiled ensemble solves the issue, I was able to train with 1024x1024 and tiles of 256x256 just fine. However the current refactor for v1 is still not finished, I'll try to get that completed asap, in the meantime you can use the pre v1 version. However I was not able to reproduce the bug you reported there.

**Comment by onkarkris** [comment] 2024-07-29 00:21
Thanks! Tiled ensemble solved the issue, I can run PatcCore will all images 1024x1024 after turning off center crop!

**Comment by blaz-r** [comment] 2024-07-29 08:03
Great 😃

**Comment by samet-akcay** [comment] 2024-07-29 08:06
Great, closing this as it can be followed here https://github.com/openvinotoolkit/anomalib/issues/1727

**Closed by samet-akcay** 2024-07-29 08:06 UTC
