### ISSUE TITLE
some thing wrong with my ground truth mask visualization

### ISSUE THREAD

**Issue by ozeen** [openvinotoolkit/anomalib#1006] opened 2023-04-07 02:33 UTC
I'm using RSDDS dataset which image size is pretty small(64,64) after preprocess to train a anomaly detection model Padim with this lib, I modificated the 'image_size' parameter in config file and ran the tools/train.py, however, after training, there are something wrong with the 'Ground Truth Mask' shown in the 'results' directory, the ground truth mask should be a binary mask with a foreground and background, but after resized from (64,64) to a bigger image size and visualiization, there are many backgorund point appeared in the foreground of ground truth mask, what could be the reason for this?

**Comment by samet-akcay** [comment] 2023-04-11 21:29
Hi @ozeen, in order to reproduce the issue, can you provide your config file, the CLI command that you ran and output of the error stack? You could follow the [Bug report](https://github.com/openvinotoolkit/anomalib/issues/new?assignees=&labels=&template=bug_report.yaml&title=%5BBug%5D%3A+) link.

**Comment by ozeen** [comment] 2023-04-14 01:59
Thank you, I think I know what's the problem, the presented masks of the dataset that I'm using are not exactly two-level images.

**Comment by djdameln** [comment] 2023-04-14 10:24
That would explain your issue then. The ground truth masks are expected to be binary images with 0 for normal pixels and 255 for anomalous pixels.

**Comment by djdameln** [comment] 2023-04-14 10:24
Closing this as the issue is not on the Anomalib side.

**Closed by djdameln** 2023-04-14 10:24 UTC
