### ISSUE TITLE
[Task]: Get different image_AUROC score every time when train the ganomaly model

### ISSUE THREAD

**Issue by FFFox-abc** [openvinotoolkit/anomalib#1597] opened 2024-01-09 04:52 UTC
Thank you for provide this useful lab.
When I try to test the gannomaly model. I find it the image_AUROC score is changed and the image_F1Score is always same. 
I find the seed was fixed to 42 in config file. So I wanna know how is this happen? And when I test on PADIM it‘s stable
And if I can modify the train process of gannomaly model. like change the loss function or and more strcuture in the model 
![image](https://github.com/openvinotoolkit/anomalib/assets/54694740/201fb0bd-7123-4aef-9961-e8778d180288)
![image](https://github.com/openvinotoolkit/anomalib/assets/54694740/33be365f-e88a-40c9-9c53-79de948d6ed1)

**Comment by samet-akcay** [comment] 2024-01-12 08:57
Duplicate of #1093, which we will address later on

**Closed by samet-akcay** 2024-01-12 08:57 UTC
Labels: Task
