### ISSUE TITLE
[Bug]:  Can't run the 'getting_started' notebook 

### ISSUE THREAD

**Issue by shanmugamani1023** [openvinotoolkit/anomalib#1692] opened 2024-01-30 10:00 UTC
### Describe the bug

datamodule = MVTec('sample_data')
datamodule.prepare_data()  # Downloads the dataset if it's not in the specified `root` directory
datamodule.setup()  # Create train/val/test/prediction sets.

i, data = next(enumerate(datamodule.val_dataloader()))
print(data.keys())

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

I tried both following methods to prepare a dataset ,but datamodule.setup() produce Error ValueError: Access denied: Path is outside the allowed directory

1. datamodule = MVTec(root="/root")
datamodule.prepare_data() 
# datamodule.setup()
# Downloads the dataset if it's not in the specified `root` directory
datamodule.setup()  # Create train/val/test/prediction sets.

i, data = next(enumerate(datamodule.val_dataloader()))
print(data.keys())

2. datamodule = MVTec()
datamodule.prepare_data() 
# datamodule.setup()
# Downloads the dataset if it's not in the specified `root` directory
datamodule.setup()  # Create train/val/test/prediction sets.

i, data = next(enumerate(datamodule.val_dataloader()))
print(data.keys())

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

datamodule = MVTec(root="/root")
datamodule.prepare_data() 
# datamodule.setup()
# Downloads the dataset if it's not in the specified `root` directory
datamodule.setup()  # Create train/val/test/prediction sets.

i, data = next(enumerate(datamodule.val_dataloader()))
print(data.keys())

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[14], line 3
      1 datamodule = MVTec(root="/root")
      2 datamodule.prepare_data() 
----> 3 datamodule.setup()
      4 # Downloads the dataset if it's not in the specified `root` directory
      5 datamodule.setup()  # Create train/val/test/prediction sets.

File ~\.conda\envs\anamolib\Lib\site-packages\anomalib\data\base\datamodule.py:103, in AnomalibDataModule.setup(self, stage)
     96 """Set up train, validation and test data.
     97 
     98 Args:
     99     stage: str | None:  Train/Val/Test stages.
    100         Defaults to ``None``.
    101 """
    102 if not self.is_setup:
--> 103     self._setup(stage)
    104 assert self.is_setup

File ~\.conda\envs\anamolib\Lib\site-packages\anomalib\data\base\datamodule.py:121, in AnomalibDataModule._setup(self, _stage)
    118 assert self.train_data is not None
    119 assert self.test_data is not None
--> 121 self.train_data.setup()
    122 self.test_data.setup()
    124 self._create_test_split()

File ~\.conda\envs\anamolib\Lib\site-packages\anomalib\data\base\dataset.py:168, in AnomalibDataset.setup(self)
    166 """Load data/metadata into memory."""
    167 if not self.is_setup:
--> 168     self._setup()
    169 assert self.is_setup, "setup() should set self._samples"

File ~\.conda\envs\anamolib\Lib\site-packages\anomalib\data\image\mvtec.py:236, in MVTecDataset._setup(self)
    235 def _setup(self) -> None:
--> 236     self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)

File ~\.conda\envs\anamolib\Lib\site-packages\anomalib\data\image\mvtec.py:131, in make_mvtec_dataset(root, split, extensions)
    128 if extensions is None:
    129     extensions = IMG_EXTENSIONS
--> 131 root = validate_path(root)
    132 samples_list = [(str(root),) + f.parts[-3:] for f in root.glob(r"**/*") if f.suffix in extensions]
    133 if not samples_list:

File ~\.conda\envs\anamolib\Lib\site-packages\anomalib\data\utils\path.py:217, in validate_path(path, base_dir, should_exist)
    215 if not str(path).startswith(str(base_dir)):
    216     msg = "Access denied: Path is outside the allowed directory"
--> 217     raise ValueError(msg)
    219 # In case path ``should_exist``, the path is valid, and should be
    220 # checked for read and execute permissions.
    221 if should_exist:
    222     # Check if the path exists

ValueError: Access denied: Path is outside the allowed directory

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
N/A
```

### Logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment] 2024-01-30 10:09
Hi @shanmugamani1023, thanks for reporting this. For security reasons, we had to add a `validate_path` function, which is the cause of this when your data is not in your base directory. 

Since this is a duplicate of #1688, I'll be closing this. You could check that out for now until we address this. We're working on it

**Closed by samet-akcay** 2024-01-30 10:09 UTC
