### ISSUE TITLE
[Bug]: Installation Error: Invalid requirement: 'torch>=2+cu121'

### ISSUE THREAD

**Issue by nickjyj** [openvinotoolkit/anomalib#2211] opened 2024-07-23 19:50 UTC
### Describe the bug

I cloned the anomalib repo and switched to v1.1.0. 
Following the Installation instructions on github:
1. `pip install -e .`
2. `anomalib install --option core`

The second command generated the error as below:
![Screenshot 2024-07-23 154627](https://github.com/user-attachments/assets/2f4e5fb5-5041-47b8-8c4f-b8e78fd0e8e4)

Also, I tried both on Windows and Ubuntu. It failed on both OS.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

AS shown in Description

### OS information

N/A

### Expected behavior

It should be installed successfully

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
NA
```

### Logs

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hafid-Qa** [comment] 2024-07-24 03:02
By downgrading `pip` and `setuptools`, I got it to work.  
 Check this #2206 
`pip install --upgrade pip==24.0 setuptools==69.5.1  anomalib`

**Comment by samet-akcay** [comment] 2024-07-24 08:23
Duplicate of #2156. We are aware of this, and will try to push a fix.

**Closed by samet-akcay** 2024-07-24 08:23 UTC
