### ISSUE TITLE
Fastflow onnx export fails

### ISSUE THREAD

**Issue by hanhan1990** [openvinotoolkit/anomalib#724] opened 2022-11-21 06:22 UTC
Fastflow onnx export fails

![1669011725(1)](https://user-images.githubusercontent.com/61170428/202979544-aa26b95a-defe-4400-8ea3-c6b725df90a7.png)

OS: Windows10
-torch: 1.12.0
pytorch-lightning: 1.6.5
-anomalib: 0.3.7
OpenVINO Version [v2021.4.2]
onnx: 1.12.0

**Comment by samet-akcay** [comment] 2022-11-22 05:19
@hanhan1990 thanks for reporting this. Looks like this is a duplicate of #706. I'm closing this one. You could track the progress from there.

**Closed by samet-akcay** 2022-11-22 05:19 UTC
