### ISSUE TITLE
result is far worse than benchmark result

### ISSUE THREAD

**Issue by BOX-LEO** [openvinotoolkit/anomalib#787] opened 2022-12-13 20:50 UTC
### Describe the bug

result of patchcore on MVTec is a lot worse than result report on model page, result of carpet was uploaded.

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

run code in colab example, 
change config.yalm of patchcore using python yalm library:
```
import yaml

yalm_path = '/content/anomalib/anomalib/models/patchcore/config.yaml'
with open(yalm_path) as f:
     list_doc = yaml.safe_load(f)

list_doc['dataset']['category'] = 'carpet'

with open(yalm_path, "w") as f:
    yaml.dump(list_doc, f)
```
run patchcore by:
```
%cd /content/anomalib/
!python tools/train.py --config anomalib/models/patchcore/config.yaml
```

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: 3
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: T4
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

image auroc 0.984

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
dataset:
  name: mvtec #options: [mvtec, btech, folder]
  format: mvtec
  path: ./datasets/MVTec
  task: segmentation
  category: carpet
  image_size: 224
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.
```

### Logs

```shell
2022-12-13 20:26:28,454 - pytorch_lightning.utilities.seed - INFO - Global seed set to 42
2022-12-13 20:26:28,455 - anomalib.data - INFO - Loading the datamodule
2022-12-13 20:26:28,456 - anomalib.pre_processing.pre_process - WARNING - Transform configs has not been provided. Images will be normalized using ImageNet statistics.
2022-12-13 20:26:28,456 - anomalib.pre_processing.pre_process - WARNING - Transform configs has not been provided. Images will be normalized using ImageNet statistics.
2022-12-13 20:26:28,456 - anomalib.models - INFO - Loading the model.
2022-12-13 20:26:28,462 - anomalib.models.components.base.anomaly_module - INFO - Initializing PatchcoreLightning model.
/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2022-12-13 20:26:30,490 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
2022-12-13 20:26:30,783 - anomalib.utils.loggers - INFO - Loading the experiment logger(s)
2022-12-13 20:26:30,783 - anomalib.utils.callbacks - INFO - Loading the callbacks
/usr/local/lib/python3.7/dist-packages/anomalib/utils/callbacks/__init__.py:143: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2022-12-13 20:26:30,789 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: True, used: True
2022-12-13 20:26:30,789 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2022-12-13 20:26:30,789 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2022-12-13 20:26:30,789 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2022-12-13 20:26:30,790 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
2022-12-13 20:26:30,790 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2022-12-13 20:26:30,790 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2022-12-13 20:26:30,790 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
2022-12-13 20:26:30,790 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2022-12-13 20:26:30,790 - anomalib - INFO - Training the model.
2022-12-13 20:26:30,797 - anomalib.data.mvtec - INFO - Found the dataset.
2022-12-13 20:26:30,798 - anomalib.data.mvtec - INFO - Setting up train, validation, test and prediction datasets.
2022-12-13 20:26:30,808 - numexpr.utils - INFO - NumExpr defaulting to 2 threads.
/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py:611: UserWarning: Checkpoint directory /content/anomalib/results/patchcore/mvtec/carpet/weights exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
2022-12-13 20:26:34,600 - pytorch_lightning.accelerators.gpu - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/optimizer.py:184: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  "`LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer",
2022-12-13 20:26:34,606 - pytorch_lightning.callbacks.model_summary - INFO - 
  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | image_threshold       | AnomalyScoreThreshold    | 0     
1 | pixel_threshold       | AnomalyScoreThreshold    | 0     
2 | model                 | PatchcoreModel           | 24.9 M
3 | image_metrics         | AnomalibMetricCollection | 0     
4 | pixel_metrics         | AnomalibMetricCollection | 0     
5 | normalization_metrics | MinMax                   | 0     
-------------------------------------------------------------------
24.9 M    Trainable params
0         Non-trainable params
24.9 M    Total params
99.450    Total estimated model params size (MB)
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Epoch 0:   0% 0/13 [00:00<?, ?it/s] /usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/optimization/optimizer_loop.py:137: UserWarning: `training_step` returned `None`. If this was on purpose, ignore this warning...
  self.warning_cache.warn("`training_step` returned `None`. If this was on purpose, ignore this warning...")

Validation: 0it [00:00, ?it/s]2022-12-13 20:26:42,605 - anomalib.models.patchcore.lightning_model - INFO - Aggregating the embedding extracted from the training set.
2022-12-13 20:26:42,607 - anomalib.models.patchcore.lightning_model - INFO - Applying core-set subsampling to get the embedding.

Validation:   0% 0/4 [00:00<?, ?it/s]
Validation DataLoader 0:   0% 0/4 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/anomalib/models/patchcore/torch_model.py:182: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  weights = (1 - F.softmax(distances.squeeze()))[..., 0]

Validation DataLoader 0: 100% 4/4 [00:03<00:00,  1.11it/s]
Epoch 0: 100% 13/13 [02:21<00:00, 10.88s/it, loss=nan, pixel_F1Score=0.550, pixel_AUROC=0.986]
Epoch 0: 100% 13/13 [02:22<00:00, 10.97s/it, loss=nan, pixel_F1Score=0.550, pixel_AUROC=0.986]
2022-12-13 20:28:58,004 - anomalib.utils.callbacks.timer - INFO - Training took 143.40 seconds
2022-12-13 20:28:58,005 - anomalib - INFO - Loading the best model weights.
2022-12-13 20:28:58,005 - anomalib - INFO - Testing the model.
2022-12-13 20:28:58,013 - anomalib.data.mvtec - INFO - Found the dataset.
2022-12-13 20:28:58,013 - anomalib.data.mvtec - INFO - Setting up train, validation, test and prediction datasets.
2022-12-13 20:28:58,129 - pytorch_lightning.accelerators.gpu - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2022-12-13 20:28:58,132 - anomalib.utils.callbacks.model_loader - INFO - Loading the model from /content/anomalib/results/patchcore/mvtec/carpet/weights/model-v6.ckpt
Testing DataLoader 0: 100% 4/4 [00:32<00:00,  8.13s/it]2022-12-13 20:29:34,763 - anomalib.utils.callbacks.timer - INFO - Testing took 36.42465543746948 seconds
Throughput (batch_size=32) : 3.212110000624574 FPS
Testing DataLoader 0: 100% 4/4 [00:33<00:00,  8.25s/it]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       image_AUROC          0.3695826828479767
      image_F1Score         0.8640776872634888
       pixel_AUROC          0.9861111640930176
      pixel_F1Score          0.550082802772522
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment] 2022-12-14 04:28
Duplicate of #715

**Comment by samet-akcay** [comment] 2022-12-14 04:28
Hi @BOX-LEO, you could join the discussion in #715

**Closed by samet-akcay** 2022-12-14 04:28 UTC
