### ISSUE TITLE
Does patchcore not support changing pre-training weights for the time being? I want to replace wide_resnet50_2 with efficientnet_b3, what do I do

### ISSUE THREAD

**Issue by luoyq6** [openvinotoolkit/anomalib#1869] opened 2024-03-18 07:35 UTC
### What is the motivation for this task?

 I want to replace wide_resnet50_2 with efficientnet_b3

### Describe the solution you'd like

what do I do?

**Comment by luoyq6** [comment] 2024-03-19 01:57
@blaz-r

**Comment by samet-akcay** [comment] 2024-03-19 08:58
You could refer to this documentation
https://anomalib.readthedocs.io/en/latest/markdown/guides/how_to/models/feature_extractors.html

Since this is a duplicate of https://github.com/openvinotoolkit/anomalib/discussions/1874, I'm closing this. We could continue the discussion there. Thanks!

**Closed by samet-akcay** 2024-03-19 08:58 UTC
Labels: Task

**Comment by luoyq6** [comment] 2024-03-19 09:21
ok ,Thank you

**Comment by luoyq6** [comment] 2024-03-19 09:27
No weight initialization
![image](https://github.com/openvinotoolkit/anomalib/assets/110521846/e0ba1d61-2899-48ea-8864-05c66bcc6ee6)
@samet-akcay

**Comment by luoyq6** [comment] 2024-03-19 09:28
![image](https://github.com/openvinotoolkit/anomalib/assets/110521846/6c02eb30-61d3-4c7b-86fc-b27bfdec15a4)

**Comment by samet-akcay** [comment] 2024-03-19 09:50
Can you share your code? From the first glance, `pre_trained` flag may not be setup properly, but it is hard to tell without seeing the code or config.

**Comment by luoyq6** [comment] 2024-03-20 02:13
[patchcore_code.zip](https://github.com/openvinotoolkit/anomalib/files/14661355/patchcore_code.zip)
OK, the main code is in here,
![image](https://github.com/openvinotoolkit/anomalib/assets/110521846/a0b24023-33bd-4272-9259-d1ec6029cb69)

**Comment by luoyq6** [comment] 2024-03-20 02:14
@samet-akcay

**Comment by blaz-r** [comment] 2024-03-20 23:38
I think it's possible, as the error suggests, that the weights are not available under this specific name. Also as Samet said, please share all the code you use, as it might be an issue with pre_trained flag in torch model.

**Comment by watertianyi** [comment] 2024-11-01 03:49
@blaz-r 
I used convnextv2_huge.fcmae_ft_in22k_in1k_512 to replace the pre-trained network wide_resnet50_2 in patchcore, and used layers=['stages.1', 'stages.2'] for classification. The indicator effect is far worse than wide_resnet50_2. Isn't convnextv2 better than wide_resnet50_2? Why Would it be so bad?
