### ISSUE TITLE
[Bug]: engine.test plots the anomalies in heatmap in wrong place when a cutout transform is used

### ISSUE THREAD

**Issue by stevensagaert** [openvinotoolkit/anomalib#2247] opened 2024-08-13 08:04 UTC
### Describe the bug

I've added a transform to both traning & validation that cuts out a portion of the image to be able to use higher res. When engine.test is performed and the heatmaps are plotted the hotspots are in the wrong place.

### Dataset

Folder

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

EfficientAD model.
here's the transform:
class TopLeftCornerCrop(object):
    def __init__(self,x,y,width,height):
        self.x=x
        self.y=y
        self.width = width
        self.height = height

    def __call__(self, img):
        return F.crop(img,self.y,self.x,self.height, self.width)

transf=Compose([TopLeftCornerCrop(0,75,800,957),Resize((512, 512))])

datamodule = Folder(
    name="ABC",
    root="data",
    normal_dir="normal",
    abnormal_dir="abnormal",
    task=TaskType.CLASSIFICATION,
    seed=13,
    train_batch_size=1,  #for EfficientAD this must be 1 !!! 
    eval_batch_size=1, # set to 1 to be able to run with higher res on laptop. for default 256*256 res you can leave eval_batch_size away
    train_transform=transf, #Note: for EfficientAD you need to do the resize or by default the input will be resized to (256,256). remove this if it doesn't improve the diffuse sprays. Note: the resize gives an error so training is not working at this time!
    eval_transform=transf
)

### OS information

OS information:
- OS:  Ubuntu 22.04
- Python version: 3.10.12
- Anomalib version: 1.1.0
- PyTorch version: 2.2.2
- CUDA/cuDNN version: 12.1.105
- GPU models and configuration: Quadro T2000
- Any other relevant information: I'm using a custom dataset

### Expected behavior

when plotting heatmap either the cutout picture should be used or when using the full original picture (like it is now) the the cutout should be reversed properly.

### Screenshots

![image](https://github.com/user-attachments/assets/8aa7dd21-8fee-414e-9c8b-73764e52e1c9)

### Pip/GitHub

pip

### Configuration YAML

```yaml
I use code
```

### Logs

```shell
no specific errors in logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexriedel1** [comment] 2024-08-13 08:46
This PR https://github.com/openvinotoolkit/anomalib/pull/2063 might solve the issue

**Comment by samet-akcay** [comment] 2024-08-15 09:12
Duplicate of https://github.com/openvinotoolkit/anomalib/issues/1660, which is on our roadmap

**Closed by samet-akcay** 2024-08-15 09:12 UTC
