### ISSUE TITLE
[Bug]: train_batch_size for EfficientAd should be 1.

### ISSUE THREAD

**Issue by EWAN9709** [openvinotoolkit/anomalib#2169] opened 2024-07-03 08:25 UTC
### Describe the bug

Thank you very much for your contribution. I got an error when using EfficientAd: ValueError: train_batch_size for EfficientAd should be 1. So I referred to src\anomalib\models\image\efficient_ad\README.md and used the following command: anomalib train --model EfficientAd --data anomalib.data.MVTec --data.category <category> --data.train_batch_size 1, but still got the following error:
![image](https://github.com/openvinotoolkit/anomalib/assets/82500501/dadaf5ae-2586-4690-97e3-8a5652799ab9)

Can you help me solve it?

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

anomalib train --model EfficientAd --data anomalib.data.MVTec --data.category <category> --data.train_batch_size 1

### OS information

OS information:
- OS: win10
- Python version:3.10.0
- Anomalib version: newest
- PyTorch version: 2.3.1
- CUDA/cuDNN version: 12.5
- GPU models and configuration: GeForce RTX 3090
- I'm using a custom dataset

### Expected behavior

start train EfficientAd 

### Pip/GitHub

pip

### Configuration YAML

```yaml
model:
  class_path: anomalib.models.EfficientAd
  init_args:
    teacher_out_channels: 384
    model_size: S
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true

metrics:
  pixel:
    - AUROC
    - F1Score
    - AUPRO
  image:
    - AUROC
    - F1Score

trainer:
  max_epochs: 1000
  max_steps: 70000
```

### Logs

```shell
no
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abc-125** [comment] 2024-07-09 11:14
Hi, please double-check your configuration files, especially `miniLED.yaml`. I have tried this code below, and it works:

`anomalib train --model EfficientAd --data anomalib.data.MVTec --data.category bottle --data.train_batch_size 1`

**Comment by samet-akcay** [comment] 2024-07-10 09:04
I agree with @blaz-r and @abc-125. From the error, it looks like you have `batch size` argument in your trainer config. 

I've also tried the following command and it works.
```bash
anomalib train --model EfficientAd --data anomalib.data.MVTec --data.category transistor --data.train_batch_size 1  
```
I would check the trainer config, from which I could remove `train_batch_size`

I'm closing this since I believe it is not a bug. Feel free to comment here and re-open if needed. Cheers

**Closed by samet-akcay** 2024-07-10 09:04 UTC

**Comment by suahelen** [comment] 2024-10-24 14:03
Would anyone know why excatly the batchsize has to be 1?
