### ISSUE TITLE
[Task]:  Overflowing ram

### ISSUE THREAD

**Issue by vuhungtvt142** [openvinotoolkit/anomalib#813] opened 2022-12-23 07:12 UTC
### What is the motivation for this task?

 Interrupt training

### Describe the solution you'd like

I train padim model on colab pro with gpu. when i'm training, i have problems are overflowing ram cpu, interrupt training. Batch size train is 8. Please help me to reslove this problem?
thank you!

**Comment by ashwinvaidya17** [comment] 2022-12-28 09:57
I am closing this as it looks like a duplicate of https://github.com/openvinotoolkit/anomalib/discussions/581. Feel free to reopen it if you think it is different. Otherwise you can continue the discussion there.

**Closed by ashwinvaidya17** 2022-12-28 09:57 UTC
