### ISSUE TITLE
Path separator for anomalib-1.0.0 on Windows

### ISSUE THREAD

**Issue by mitanihiroshi** [openvinotoolkit/anomalib#1849] opened 2024-03-13 08:28 UTC
anomalib-1.0.0\src\anomalib\data\utils\image.py-diff

10a11
> import os
439d439
< 
444c444,447
<         file_path = Path("/".join(str(file_path).split("/")[2:]))
---
>         if os.name == 'posix':
>             file_path = Path("/".join(str(file_path).split("/")[2:]))
>         elif os.name == 'nt':
>             file_path = Path("\\".join(str(file_path).split("\\")[2:]))

**Comment by samet-akcay** [comment] 2024-03-13 08:38
@mitanihiroshi, this is a duplicate of #1831. There is a suggested solution there as well. We just need to create a PR and merge the suggested change.

**Closed by samet-akcay** 2024-03-13 08:38 UTC
