### ISSUE TITLE
openvino_inference.py 'ImageResult' object has no attribute 'anomalous_boxes' or 'heat_map'

### ISSUE THREAD

**Issue by rvermeire** [openvinotoolkit/anomalib#1005] opened 2023-04-06 14:18 UTC
When I invoke openvino_inference.py with --task=detection or --task=segmentation I get `AttributeError: 'ImageResult' object has no attribute 'anomalous_boxes' or 'heat_map'` respectively

**Comment by samet-akcay** [comment] 2023-08-10 12:06
Hi @rvermeire, thanks for your patience. 

I am unable to reproduce this. If you are still having this issue, can you provide your config file? 

When I use the following config file I have access to those attributes:

## Training
```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  task: segmentation
  category: bottle
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: 224 # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino    # options: onnx, openvino, torch

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

```bash
# Train the patchcore model.
python tools/train.py --model patchcore
```

## Inference
When you run the openvino inference via

This would have the following 
```python
>>> from anomalib.data.utils import read_image
>>> from anomalib.deploy import OpenVINOInferencer
>>> 
>>> inferencer = OpenVINOInferencer(
...    path="results/patchcore/mvtec/bottle/run/weights/openvino/model.bin",
...    metadata="results/patchcore/mvtec/bottle/run/weights/openvino/metadata.json",
...    device="CPU",
... )
>>> image = read_image("datasets/MVTec/bottle/test/broken_large/000.png")
>>> predictions = inferencer.predict(image=image)


# This should give the output you want
>>> predictions.heat_map.shape
(900, 900, 3)

>>> predictions.anomaly_map.shape
(900, 900)
```

**Comment by samet-akcay** [comment] 2023-08-10 13:23
Since this is irreproducible, I'm closing this. Feel free to re-open if you still have any issues. Thanks again for your patience!

**Closed by samet-akcay** 2023-08-10 13:23 UTC

**Comment by yesilyurtihsan** [comment] 2024-02-09 09:11
Ran into the same problem, trying to find what triggers this and what I missed.

**Comment by samet-akcay** [comment] 2024-02-09 09:12
@yesilyurtihsan, which version of anomalib are you using?

**Comment by yesilyurtihsan** [comment] 2024-02-09 09:26
It is 1.0.0.

**Comment by yesilyurtihsan** [comment] 2024-02-09 11:21
Found the issue!
I am working on a jupyter notebook. When I execute the cell with the code:
inferencer.predict(image)
I get the the error.
Surprisingly, when I execute the below code I don't run into any problems:
preds = inferencer.predict(image)
preds.pred_label

Sorry for saying it now but it seems like an error with jupyter as is seen in the traceback below:


AttributeError                            Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/IPython/core/formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

File ~/.local/lib/python3.10/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File ~/.local/lib/python3.10/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File ~/miniconda3/envs/anomalib/lib/python3.10/dataclasses.py:239, in _recursive_repr.<locals>.wrapper(self)
    237 repr_running.add(key)
    238 try:
--> 239     result = user_function(self)
    240 finally:
    241     repr_running.discard(key)

File <string>:3, in __repr__(self)

AttributeError: 'ImageResult' object has no attribute 'normal_boxes'

**Comment by samet-akcay** [comment] 2024-02-09 12:20
interesting find indeed!
