### ISSUE TITLE
[Question]: Patchcore predictions zoomed in

### ISSUE THREAD

**Issue by TheElectricBlender** [openvinotoolkit/anomalib#2331] opened 2024-10-01 07:13 UTC
### What is the motivation for this task?

Hi team, as per the title, i noticed that the anomaly_map from the patchcore inference is slightly zoomed in
![image](https://github.com/user-attachments/assets/5577a873-4126-4013-adad-ff76bbbd37e8)
this is the result of using efficientad instead
![image](https://github.com/user-attachments/assets/1b0ae710-9592-4269-b026-d98d7b0d5c0f)

is there a way to avoid this? so that i am able to overlay the anomaly_map with the original image properly.
I am using OpenVINOInferencer

### Describe the solution you'd like

I would like a way to overlay the anomaly_map with the original image properly.

**Comment by samet-akcay** [comment] 2024-10-01 08:25
@TheElectricBlender thanks for reporting this. We are aware of this issue, and currently working on it to address. Since this issue has previously been reported here #1460  #1447, I'm closing this one.

**Closed by samet-akcay** 2024-10-01 08:25 UTC

**Comment by samet-akcay** [comment] 2024-10-01 08:26
Duplicate of #1460 and #1447.
